models:
  - name: stg_jaffle_shop__customers
    description: Staged customer data from our jaffle shop app.
    columns: 
      - name: customer_id
        description: The primary key for customers.
        tests:
          - unique
          - not_null

  - name: stg_jaffle_shop__orders
    description: Staged order data from our jaffle shop app.
    columns: 
      - name: order_id
        description: Primary key for orders.
        tests:
          - unique
          - not_null
      - name: order_status
        description: "{{ doc('order_status') }}"
        tests:
          - accepted_values:
              values:
                - completed
                - shipped
                - returned
                - placed
                - return_pending
      - name: customer_id
        description: Foreign key to stg_customers.customer_id.
        tests:
          - relationships:
              to: ref('stg_jaffle_shop__customers')
              field: customer_id

  - name: stg_stripe__payments
    description: Staged payment data from our stripe app.
    columns: 
      - name: payment_id
        description: Primary key for payments.
        tests:
          - unique
          - not_null
      - name: payment_status
        description: "{{ doc('order_status') }}"
        tests:
          - accepted_values:
              values:
                - success
                - fail
      - name: order_id
        description: Foreign key to stg_orders.order_id.
        tests:
          - relationships:
              to: ref('stg_jaffle_shop__orders')
              field: order_id